// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/api/implementatie.go

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockImplementatieRepository is a mock of ImplementatieRepository interface.
type MockImplementatieRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImplementatieRepositoryMockRecorder
}

// MockImplementatieRepositoryMockRecorder is the mock recorder for MockImplementatieRepository.
type MockImplementatieRepositoryMockRecorder struct {
	mock *MockImplementatieRepository
}

// NewMockImplementatieRepository creates a new mock instance.
func NewMockImplementatieRepository(ctrl *gomock.Controller) *MockImplementatieRepository {
	mock := &MockImplementatieRepository{ctrl: ctrl}
	mock.recorder = &MockImplementatieRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImplementatieRepository) EXPECT() *MockImplementatieRepositoryMockRecorder {
	return m.recorder
}

// AanvraagProduct mocks base method.
func (m *MockImplementatieRepository) AanvraagProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AanvraagProduct", c)
}

// AanvraagProduct indicates an expected call of AanvraagProduct.
func (mr *MockImplementatieRepositoryMockRecorder) AanvraagProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AanvraagProduct", reflect.TypeOf((*MockImplementatieRepository)(nil).AanvraagProduct), c)
}

// GetImplementatieStatus mocks base method.
func (m *MockImplementatieRepository) GetImplementatieStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetImplementatieStatus", c)
}

// GetImplementatieStatus indicates an expected call of GetImplementatieStatus.
func (mr *MockImplementatieRepositoryMockRecorder) GetImplementatieStatus(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplementatieStatus", reflect.TypeOf((*MockImplementatieRepository)(nil).GetImplementatieStatus), c)
}

// GetInstallatieStatus mocks base method.
func (m *MockImplementatieRepository) GetInstallatieStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetInstallatieStatus", c)
}

// GetInstallatieStatus indicates an expected call of GetInstallatieStatus.
func (mr *MockImplementatieRepositoryMockRecorder) GetInstallatieStatus(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstallatieStatus", reflect.TypeOf((*MockImplementatieRepository)(nil).GetInstallatieStatus), c)
}

// GetPersoonlijkeInstellingen mocks base method.
func (m *MockImplementatieRepository) GetPersoonlijkeInstellingen(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPersoonlijkeInstellingen", c)
}

// GetPersoonlijkeInstellingen indicates an expected call of GetPersoonlijkeInstellingen.
func (mr *MockImplementatieRepositoryMockRecorder) GetPersoonlijkeInstellingen(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersoonlijkeInstellingen", reflect.TypeOf((*MockImplementatieRepository)(nil).GetPersoonlijkeInstellingen), c)
}

// GetProductInformatie mocks base method.
func (m *MockImplementatieRepository) GetProductInformatie(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetProductInformatie", c)
}

// GetProductInformatie indicates an expected call of GetProductInformatie.
func (mr *MockImplementatieRepositoryMockRecorder) GetProductInformatie(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductInformatie", reflect.TypeOf((*MockImplementatieRepository)(nil).GetProductInformatie), c)
}

// Healthcheck mocks base method.
func (m *MockImplementatieRepository) Healthcheck(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Healthcheck", c)
}

// Healthcheck indicates an expected call of Healthcheck.
func (mr *MockImplementatieRepositoryMockRecorder) Healthcheck(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthcheck", reflect.TypeOf((*MockImplementatieRepository)(nil).Healthcheck), c)
}

// InstalleerProduct mocks base method.
func (m *MockImplementatieRepository) InstalleerProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InstalleerProduct", c)
}

// InstalleerProduct indicates an expected call of InstalleerProduct.
func (mr *MockImplementatieRepositoryMockRecorder) InstalleerProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstalleerProduct", reflect.TypeOf((*MockImplementatieRepository)(nil).InstalleerProduct), c)
}

// LeverProduct mocks base method.
func (m *MockImplementatieRepository) LeverProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LeverProduct", c)
}

// LeverProduct indicates an expected call of LeverProduct.
func (mr *MockImplementatieRepositoryMockRecorder) LeverProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeverProduct", reflect.TypeOf((*MockImplementatieRepository)(nil).LeverProduct), c)
}

// MarkeerAlsGeimplementeerd mocks base method.
func (m *MockImplementatieRepository) MarkeerAlsGeimplementeerd(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkeerAlsGeimplementeerd", c)
}

// MarkeerAlsGeimplementeerd indicates an expected call of MarkeerAlsGeimplementeerd.
func (mr *MockImplementatieRepositoryMockRecorder) MarkeerAlsGeimplementeerd(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkeerAlsGeimplementeerd", reflect.TypeOf((*MockImplementatieRepository)(nil).MarkeerAlsGeimplementeerd), c)
}

// OntvangProduct mocks base method.
func (m *MockImplementatieRepository) OntvangProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OntvangProduct", c)
}

// OntvangProduct indicates an expected call of OntvangProduct.
func (mr *MockImplementatieRepositoryMockRecorder) OntvangProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OntvangProduct", reflect.TypeOf((*MockImplementatieRepository)(nil).OntvangProduct), c)
}

// PersonaliseerProduct mocks base method.
func (m *MockImplementatieRepository) PersonaliseerProduct(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PersonaliseerProduct", c)
}

// PersonaliseerProduct indicates an expected call of PersonaliseerProduct.
func (mr *MockImplementatieRepositoryMockRecorder) PersonaliseerProduct(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersonaliseerProduct", reflect.TypeOf((*MockImplementatieRepository)(nil).PersonaliseerProduct), c)
}