# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'
     
    - name: Build service discovery
      run: |
        cd service-discovery
        env GOOS=windows go build -o service_discovery.exe
        env GOOS=linux GOARCH=arm go build -o app_service_discovery
        
      
    - name: Build service signaling
      run: |
        cd service-signalering
        env GOOS=windows go build -o service-signalering.exe
        env GOOS=linux GOARCH=arm go build -o app_service_signalering
        
      
    - name: Build technology selection
      run: |
        cd technology-selection
        env GOOS=windows go build -o service-technology.exe
        env GOOS=linux GOARCH=arm go build -o app_service_technology
        
      
    - name: Upload windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app_win
        path: |
          service-discovery/service_discovery.exe
          sservice-signalering/ervice_signalering.exe
          technology-selection/service-technology.exe
          technology-selection/deploy
          technology-selection/config.json
        
    - name: Upload linux build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app_linux
        path: |
          service-discovery/app_service_discovery
          service-signalering/app_service_signalering
          technology-selection/app_service_technology
          technology-selection/deploy
          technology-selection/config.json
