# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'
        
    - name: Build
      run: go build -v ./service-discovery/main.go

    - name: Test
      run: go test -v ./service-discovery/main.go
      
    - name: Generate windows build artifacts
      run: env GOOS=windows cd service-discovery go build -o service_discovery.exe
      
    - name: Generate linux build artifacts
      run: env GOOS=linux GOARCH=arm cd service-discovery go build -o app_service_discovery
      
    - name: Generate windows build artifacts
      run: env GOOS=windows go build -o service-financiering.exe ./service-financiering/main.go
      
    - name: Generate linux build artifacts
      run: env GOOS=linux GOARCH=arm go build -o app_service_financiering ./service-financiering/main.go
      
    - name: Generate windows build artifacts
      run: env GOOS=windows go build -o service-signalering.exe ./service-signalering/main.go
      
    - name: Generate linux build artifacts
      run: env GOOS=linux GOARCH=arm go build -o app_service_signalering ./service-signalering/main.go
      
    - name: Upload windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app_win
        path: |
          service_discovery.exe
          service_financiering.exe
          service_signalering.exe
        
    - name: Upload linux build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app_linux
        path: |
          app_service_discovery
          app_service_financiering
          app_service_signalering
